package com.example.auth_service.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import java.time.Instant;
import lombok.Data;

/**
 * One-time verification token associated with a single user.
 *
 * <p>The database stores only a hash of the raw token value. The raw token is generated by the
 * service and delivered out-of-band (email) to the user. This record also tracks lifecycle events
 * such as consumption and revocation for auditability and replay protection.
 */
@Data
@Entity
@Table(name = "verification_tokens")
public class VerificationToken {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    // Stored as a hash in the database. Column name is `token` for backwards compatibility.
    @Column(name = "token", nullable = false, unique = true)
    private String tokenHash;

    // Time after which the token must no longer be accepted.
    @Column(name = "expiry_date", nullable = false)
    private Instant expiresAt;

    // Creation timestamp (used for auditing and rate-limiting diagnostics).
    @Column(name = "created_at")
    private Instant createdAt = Instant.now();

    // Set when the token has been successfully used (prevents replay).
    @Column(name = "consumed_at")
    private Instant consumedAt;

    // Set when the token has been invalidated before expiry (e.g., reissue).
    @Column(name = "revoked_at")
    private Instant revokedAt;

    // Owner of this token; one token record per user.
    @OneToOne(optional = false)
    @JoinColumn(name = "user_id", nullable = false, unique = true)
    private UserAccount user;
}
